// File generated by FlutterFire CLI.
// ===========================================================================
// ⚠️ PLACEHOLDER FILE — replace this by running:
//
//     dart pub global activate flutterfire_cli
//     flutterfire configure
//
// from the project root (needs a Firebase project + you logged into the
// Firebase CLI). That command overwrites this file automatically with your
// real project's keys and also drops google-services.json /
// GoogleService-Info.plist in the right folders.
//
// If you'd rather fill this in by hand, get each value from:
// Firebase Console → Project settings → General → Your apps → SDK setup
// and config (for Android) / the Firebase config snippet (for Web).
// ===========================================================================
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh24uYRrnSmXJLW5Pg9P9kRuL75Xtq-Wk',
    appId: '1:1069568778365:web:189dbb20061ed155b71114',
    messagingSenderId: '1069568778365',
    projectId: 'ride-4f466',
    authDomain: 'ride-4f466.firebaseapp.com',
    storageBucket: 'ride-4f466.firebasestorage.app',
    measurementId: 'G-GR4Z9GC39F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKeXlnzjZe1i4FRkG73OKkll2SepufxNU',
    appId: '1:1069568778365:android:fcee0ee2d340dac0b71114',
    messagingSenderId: '1069568778365',
    projectId: 'ride-4f466',
    storageBucket: 'ride-4f466.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNm9W3VjQsKqG6WiRsRWuGgIWzF0IU08Y',
    appId: '1:1069568778365:ios:7070d3f2da26efb8b71114',
    messagingSenderId: '1069568778365',
    projectId: 'ride-4f466',
    storageBucket: 'ride-4f466.firebasestorage.app',
    iosBundleId: 'com.example.secureRide',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNm9W3VjQsKqG6WiRsRWuGgIWzF0IU08Y',
    appId: '1:1069568778365:ios:7070d3f2da26efb8b71114',
    messagingSenderId: '1069568778365',
    projectId: 'ride-4f466',
    storageBucket: 'ride-4f466.firebasestorage.app',
    iosBundleId: 'com.example.secureRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh24uYRrnSmXJLW5Pg9P9kRuL75Xtq-Wk',
    appId: '1:1069568778365:web:17df658d42fbf4c2b71114',
    messagingSenderId: '1069568778365',
    projectId: 'ride-4f466',
    authDomain: 'ride-4f466.firebaseapp.com',
    storageBucket: 'ride-4f466.firebasestorage.app',
    measurementId: 'G-6ZZ31FFZ35',
  );
}
